site:
  title: TinyMCE Documentation (Dev)
  url: https://www.tiny.cloud/docs
  start_page: tinymce::index.adoc
content:
  sources:
  - url: ./
    branches: HEAD
    start_path: ./
urls:
  html_extension_style: indexify
ui:
  bundle:
    url: http://docs-theme-feature-wsrf-730.staging.tiny.cloud/ui-bundle.zip
asciidoc:
  extensions:
    - ./extensions/live-demo.js
